### ISSUE TITLE
Plugins format

### ISSUE THREAD

**Issue by TheOfficialFloW** [NeoLTK/VITAPluginsManager#1]
You can enable/disable plugins by writing [PATH] 1 (enabled) or [PATH] 0 (disabled)...

**Comment by sscssc** [comment]
Yes but with som dump and plugins, instanly dump crash on start with [path] 0 or juste no line write

Exemple:

* PCSA00147 - rinCheat

**Comment by NeoLTK** [comment]
Yes but with some dump and plugins, instanly dump crash on start with [path] 0 or juste no line write, if plugins located on " ux0:/plugins "

Exemple:
- PCSA00147 - rinCheat
